/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datasafe_yara_Engine */

#ifndef _Included_com_datasafe_yara_Engine
#define _Included_com_datasafe_yara_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datasafe_yara_Engine
 * Method:    nativeNewYaraEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_yara_Engine_nativeNewYaraEngine
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
